# Uncomment Postgres image, then:
services:
  db:
    volumes:
      - db-data:/var/lib/postgresql # Remove /data
  redis:
    image: redis
    container_name: <redisname>
    ports:
      - '6379:6379'
    volumes:
      - redis-data:/data
    environment:
      - REDIS_ARGS=--requirepass <password> --appendonly yes
    restart: unless-stopped

volumes:
  redis-data:
    driver: local
